### PR TITLE
Add support README.md for directories (like a github)

### PR DESCRIPTION
**Pull request by manfredmann**
You can see example on http://stuff.pentium02.org/

### CODE REVIEW

**Comment by idleberg** [comment]
That's great, I actually had something similar on my list, but didn't think I'd add this before 3.x. (which is already in the works). Give me some time to look through these changes.

**Comment by manfredmann** [comment]
Ok, thanks

**Comment by smartpapers** [comment]
Hello, Can anyone PLEEEASE explain me how to use this plugin? 
I am using the latest version, i.e "2.0.3 Alpha 2" 
Where is the _public folder? Where to upload these files please explain. Thankyou.

I want to show this directory.(FOLDER)
www.example.com/FOLDER

**Comment by idleberg** [comment]
@smartpapers Feel free to open a new issue, but don't hijack a pull request for your question

**Comment by idleberg** [comment]
Could you please make a clean pull-request against the `2.3-dev` branch?

**Pull request closed without merging**
